service: storePosterToS3

frameworkVersion: "=1.7.0"

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
     - Effect: Allow
       Action: "s3:*"
       Resource:
         "arn:aws:s3:::meetzam-contentdelivery-mobilehub-1569925313/*"


functions:
  backendLambda:
    handler: backendLambda.handler
