
service: getMovieInfoFromTMDB

frameworkVersion: "=1.7.0"

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/Movie2"

custom: ${file(./credentials.json)}

functions:
  backendLambda:
    handler: backendLambda.handler
    events:
      - schedule: cron(0 10 * * ? *)
    environment:
      TMDB_API_key: ${self:custom.TMDB_API_key}
      Gracenote_API_key: ${self:custom.Gracenote_API_key}
